### ISSUE TITLE
config:dump-reference should be debug:config

### ISSUE THREAD

**Issue by weaverryan** [weaverryan/the-open-source-list#9]
Enough said: config:dump-reference should be debug:config

**Comment by voronkovich** [comment]
I don't understand this. We already have the `debug:config` command. For example:
`debug:config framework` outputs the **current** FrameworkBundle configuration,
`config:dump-reference framework` outputs the **default** FrameworkBundle configuration
What's wrong here?

**Comment by weaverryan** [comment]
@voronkovich ha! Nice, I actually _didn't_ know that! `config:dump-reference` was the original name, and so basically, somebody already did this, and I didn't even know it.

This is exactly why I wanted to publish my list somewhere public :).

Thanks!

**Comment by mablae** [comment]
I also didn't know that! Also I never read symfony2 issues, cause it so messed up and cluttered. 

Hard to get an overview. Thanks, @voronkovich

**Comment by wouterj** [comment]
**Symfony top tip**: You can already use `config:dump` to execute the command, which is way shorter and easier to type (not having to search for the - key, etc.).

_Disclamer_: I don't want to propose renaming the command to this, as having `config:dump` and `config:debug` would be too confusing.

**Comment by weaverryan** [comment]
Yea, good tip - I often forget about being able to shorten commands like this!
